data: 
  n_trajectories: 400
  t_steps: 60

  ##### generation configs, blind to solver #####
  seed: 42
  x_min: 1.5
  x_max: 3.0
  noise: 0.01

gen_params:
  A_min: 3.0
  A_max: 8.0
  B_min: -5.0
  B_max: -1.0
  ##############################################

solver:

  # diff maps
  eps_diagnose: False
  epsilon: 3.0e-3
  alpha: 1
  knn: 240

  # 0-laplacian spectral basis
  M: 50

  # 1-laplacian spectral frames
  frame_retain_thres: 1.0e-4
  plot_frame_no: 36
  plot_frame_vec_scale: 0.1

  # contact form kernel vector field
  plot_W_vec_scale: 0.1

  # linear system
  verbose: True
  sg_window: 10
  chunkz: 50
  max_kernel_dim: 3
  plot_kernel_dim: 1
  plot_sym_vec_scale: 0.2 

  plot_subsample: 2000
  analytic_validation: True