# Example config file required by solver

data:
  n_trajectories: 484 # number of trajectories in data
  t_steps: 64 # number of time steps in each trajectory

solver:
  
  ##### KEY COMPUTATION PARAMETERS #####

  eps_diagnose: False # plot to determine optimal epsilon for diff maps, recommended True for first run
  epsilon: 0.01 # Tuned once per dataset by choosing a value in the centre of eps_diagnose spectrum
  alpha: 1 # diffusion map normalisation constant. Can also be 0 or 0.5 but we need 1 to recover the laplace-beltrami operator.
  knn: 100 # knn parameter, tuned by making sure max kNN radius > 3*sqrt(4*eps) in logs. 
  # if data is not large turn off knn by set to null.

  M: 36 # number of eigenfunctions of the 0-laplacian to compute. # SEC depends entirely on this truncation. 
  # Values above 20 should suffice. Above a certain M the eigen basis will just add noise and expensive computation
  # Therefore M should be as small as possible a value that can accurately reconstruct functions
  # (check Laplacian residual and x reconstruction error to inform J choice)
  frame_retain_thres: 1.0e-3 # how many basis 1 forms to retain from the overcomplete frame.
  # Lower threshold retain more of the frames, though this is likely just noise below 1e-4.
  # Alternatively can be set by parsing n_frames = dimension of manifold x M, which is the effective rank of linear system.
  max_kernel_dim: 12 # dimension of the solution space of symmetries from SVD. Each row of V.T 
  # (corresponding to smallest singular values) is a set of coefficient representing an unique symmetry vector field V.
  # Linear combinations of these symmetries should also be symmetries: Any vector field in the span of the 
  # recovered max_kernel_dim vector fields are also infinitesimal symmetry fields, trivial or not.
  
  ##### PLOTTING CONFIGS #####
  # which eigenform to plot
  plot_frame_no: 36 # any int in [0 to n_frames)
  plot_frame_vec_scale: 0.1 # overall vector scale

  # contact form kernel vector field
  plot_W_vec_scale: 0.1 # overall vector scale

  # linear system
  plot_kernel_dim: 1 # which symmetry field to plot, any int in [0 - max_kernel_dim)
  plot_sym_vec_scale: 0.2 # overall vector scale
  plot_sym_subsample: 1000 # Number of points to sample from the manifold, reduce to increase clarity

  ##### #####
  # Function calls in the main algorithm does allow for more configurability directly in code
  # though this set of configs should suffice for the solver to work with any general well-conditioned dataset